### ISSUE TITLE
Issue with detecting censors in some images

### ISSUE THREAD

**Issue by Zero3K** [natethegreate/hent-AI#5]
Some of the types of censors used by the images in https://u.teknik.io/4pTHC.zip aren't being detected by it.

**Comment by natethegreate** [comment]
I haven't looked into those images yet, but which censors in specific? As per the documentation, any type of censor that isn't a bar or mosaic is not supported.

**Comment by Zero3K** [comment]
The majority of the images use bars and mosaics. I think its the color of the bar(s) (or ones that have text on them) that causes an issue. There are a few that use words, etc. as censors.

**Comment by natethegreate** [comment]
Yeah bars that aren't near white or black won't get picked up, since it can get problematic training on uncommon colors. It is also pretty hard to perfectly mask anything under text. 

We are currently working on expanding the dataset for further training, which will help the model detect much more.

**Comment by Zero3K** [comment]
Could you use the images that  I provided to train it?

**Comment by natethegreate** [comment]
The ai is missing these normal bars because it needs more training and a bigger dataset.

Images need to be annotated by hand in order to use them for training. If you want to try annotating them, feel free to join the Discord and we can teach you how to do it.
